### ISSUE TITLE
Question concernant l'api

### ISSUE THREAD

**Issue by ney-web** [alexlemia13/anime-scraper#1]
L'api est-elle fonctionnel ?

**Comment by alexandre-scalisi** [comment]
Bonjour, c'est un petit scraper que j'ai fait pour remplir la base de données d'un site d'anime que j'ai fait en tant que projet de fin d'année à l'école.
Je m'attendais pas à ce qu'on tombe dessus donc j'ai pas prit le temps de faire une documentation et c'est pas vraiment flexible.
Tout ce que l'application fait c'est aller sur un site et récupérer des infos sur les animes qui sont sur les sites de streaming légaux ADN, crunchyroll et wakanim et les stocker dans un fichier JSON dans le dossier "assets".

Exemple:
![image](https://user-images.githubusercontent.com/50205106/129698749-c295400a-a69c-456a-9bdd-98ed2d7357df.png)

Vous pouvez également directement aller dans le dossier "assets" et ouvrir les fichiers pour voir les infos récupérées.

Le scraper parcours énormément de pages donc cela prend plus de 5 minutes pour tout récupérer ( Je viens de faire des petites modifs donc retéléchargez puis 'npm start' dans le terminal pour lancer).
Je pense faire une api au lieu d'un scraper dans 1-2 mois pour que l'application soit plus flexible et aussi pour pas déranger le site sur lequel je fais le scraping.

En attendant, dites moi quel genre d'informations vous vouliez récupérer et je pourrais peut être faire un script qui récupère ce que vous vouliez.

Bonne journée

**Comment by ney-web** [comment]
Salut, en fait en ce moment je suis à la recherche d'une api de scraping pour crée mon site. Et j'aimerai savoir si tu avais un telegram pour qu'on puisse en discuter ?

**Comment by alexandre-scalisi** [comment]
Salut, j'ai pas telegram mais je peux le télécharger sinon mon discord c'est Alex1#6523

**Comment by ney-web** [comment]
Ouais tu pourrais télécharger, j'ai un problème avec discord j'ai plus de carte sim donc je peux plus faire de compte, mon telegram @ney1337
